// Eight fake cards. Vary reading time and status so filters have something to bite on.
window.PROTO_CARDS = [
  { id: 'c1', url: 'https://alpha.substack.com/p/questions', title: 'How Great Questions Change a Company', author: 'A. Writer', publication: 'Alpha Notes', estimatedReadingMinutes: 12, status: 'to_read', savedAt: '2026-08-10', notes: '', quotes: [], exportVersion: 0, sortOrder: 0 },
  { id: 'c2', url: 'https://beta.substack.com/p/slow-reading', title: 'In Defense of Slow Reading', author: 'B. Essayist', publication: 'Beta Letters', estimatedReadingMinutes: 6, status: 'to_read', savedAt: '2026-08-11', notes: '', quotes: [], exportVersion: 0, sortOrder: 1 },
  { id: 'c3', url: 'https://gamma.substack.com/p/40-min', title: 'The Long One About Infrastructure', author: 'C. Analyst', publication: 'Gamma Report', estimatedReadingMinutes: 41, status: 'to_read', savedAt: '2026-08-12', notes: '', quotes: [], exportVersion: 0, sortOrder: 2 },
  { id: 'c4', url: 'https://delta.substack.com/p/paywalled', title: 'A Paid Piece With No Estimate', author: 'D. Columnist', publication: 'Delta Weekly', estimatedReadingMinutes: undefined, status: 'to_read', savedAt: '2026-08-13', notes: '', quotes: [], exportVersion: 0, sortOrder: 3 },
  { id: 'c5', url: 'https://alpha.substack.com/p/second', title: 'Second Alpha Post, Half Read', author: 'A. Writer', publication: 'Alpha Notes', estimatedReadingMinutes: 9, status: 'reading', savedAt: '2026-08-05', notes: 'Strong opening. Skeptical of section 3.', quotes: [{ text: 'Questions are cheaper than answers.', comment: 'Steal this line.', capturedAt: '2026-08-14' }], exportVersion: 0, sortOrder: 0 },
  { id: 'c6', url: 'https://epsilon.substack.com/p/short', title: 'Five Minute Note on Habits', author: 'E. Coach', publication: 'Epsilon Daily', estimatedReadingMinutes: 5, status: 'reading', savedAt: '2026-08-06', notes: '', quotes: [], exportVersion: 0, sortOrder: 1 },
  { id: 'c7', url: 'https://zeta.substack.com/p/done', title: 'Already Processed and Exported', author: 'Z. Author', publication: 'Zeta Review', estimatedReadingMinutes: 15, status: 'processed', savedAt: '2026-07-28', notes: 'Exported once.', quotes: [], exportVersion: 1, sortOrder: 0 },
  { id: 'c8', url: 'https://eta.substack.com/p/done-2', title: 'Processed Twice', author: 'H. Writer', publication: 'Eta Letters', estimatedReadingMinutes: 22, status: 'processed', savedAt: '2026-07-20', notes: 'Second export fixed a typo.', quotes: [{ text: 'A quote with a lost location.', locatorLost: true, capturedAt: '2026-07-25' }], exportVersion: 2, sortOrder: 1 },
];